# https://taskfile.dev

version: '3'

tasks:

  build-docker-ubuntu-non-root-image:
    cmd: docker build -t ubuntu-non_root:noble -f Dockerfile.ubuntu-non_root .
  
  wayland:
    deps: [build-docker-ubuntu-non-root-image]
    cmds:
      - docker build -t wayland-build:0.1 -f Dockerfile.wayland .
      - docker run --mount type=bind,src=/usr/local,dst=/usr/local wayland-build:0.1
  
  wayland-protocols:
    deps: [wayland]
    cmds:
      - docker build -t wayland-protocols-build:0.1 -f Dockerfile.wayland-protocols .
      - docker run --mount type=bind,src=/usr/local,dst=/usr/local wayland-protocols-build:0.1
  
  libdisplay-info:
    deps: [build-docker-ubuntu-non-root-image]
    cmds:
      - docker build -t libdisplay-info-build:0.1 -f Dockerfile.libdisplay-info .
      - docker run --mount type=bind,src=/usr/local,dst=/usr/local libdisplay-info-build:0.1
  
  libinput:
    deps: [build-docker-ubuntu-non-root-image]
    cmds:
      - docker build -t libinput-build:0.1 -f Dockerfile.libinput .
      - docker run --mount type=bind,src=/usr/local,dst=/usr/local libinput-build:0.1
  
  libxcb-errors:
    deps: [build-docker-ubuntu-non-root-image]
    cmds:
      - docker build -t libxcb-errors-build:0.1 -f Dockerfile.libxcb-errors .
      - docker run --mount type=bind,src=/usr/local,dst=/usr/local libxcb-errors-build:0.1


  build-all:
    deps: [build-docker-ubuntu-non-root-image,wayland,wayland-protocols,libdisplay-info,libinput,libxcb-errors]
