# https://taskfile.dev

version: "3"

includes:
  deps:
    taskfile: ./deps
    flatten: true

env:
  CMAKE: "{{.HOME}}/.local/cmake-{{.CMAKE_VERSION}}-linux-x86_64/bin/cmake"
  PREFIX: "/usr/local"
  HYPR_DIR: "{{.PWD}}/hypr"
  CC: "{{.PREFIX}}/bin/gcc"
  CXX: "{{.PREFIX}}/bin/g++"
  CMAKE_PREFIX_PATH: "/usr/local:/usr"
  PKG_CONFIG_PATH: "/usr/local/lib/pkgconfig:/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig"

tasks:
  cmake:
    dir: "$HOME/.local"
    vars:
      CMAKE_VERSION: "4.1.2"
    cmds:
      - sudo apt-get update -y
      - sudo apt-get install -y wget tar gzip
      - mkdir -p "{{.HOME}}/.local"
      - wget "https://github.com/Kitware/CMake/releases/download/v{{.CMAKE_VERSION}}/cmake-{{.CMAKE_VERSION}}-linux-x86_64.tar.gz"
      - tar -xvzf "cmake-{{.CMAKE_VERSION}}-linux-x86_64.tar.gz"
    status:
      - test -f cmake-{{.CMAKE_VERSION}}-linux-x86_64/bin/cmake

  hyprwayland-scanner:
    deps: [gcc, cmake]
    vars:
      VERSION: "0.4.5"
    cmds:
      - sudo apt-get install -y git build-essential wget libpugixml-dev tar gzip pkgconf pkg-config
      - wget https://github.com/hyprwm/{{.TASK}}/archive/refs/tags/v{{.VERSION}}.tar.gz
      - tar -xvzf v{{.VERSION}}.tar.gz
      - |
        cd {{.TASK}}-{{.VERSION}}
        $CMAKE -DCMAKE_INSTALL_PREFIX=$PREFIX -B build
        $CMAKE --build build --parallel
        sudo $CMAKE --install build
    status:
      - test -f $PREFIX/bin/hyprwayland-scanner

  hyprutils:
    dir: "{{.PWD}}/hypr"
    deps: [gcc, cmake]
    vars:
      VERSION: "0.10.1"
    cmds:
      - sudo apt-get install -y git build-essential wget tar gzip pkgconf pkg-config libpixman-1-dev
      - wget https://github.com/hyprwm/hyprutils/archive/refs/tags/v{{.VERSION}}.tar.gz
      - tar -xvzf v{{.VERSION}}.tar.gz
      - |
        cd hyprutils-{{.VERSION}}
        $CMAKE --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX -S . -B ./build
        $CMAKE --build ./build --config Release --target all -j`nproc 2>/dev/null || getconf NPROCESSORS_CONF`
        sudo $CMAKE --install build
    status:
      - test -f $PREFIX/lib/libhyprutils.so

  hyprlang:
    dir: "{{.PWD}}/hypr"
    deps: [hyprutils]
    vars:
      VERSION: "0.6.5"
    env:
      CC: "{{.PREFIX}}/bin/gcc"
      CXX: "{{.PREFIX}}/bin/g++"
      CMAKE_PREFIX_PATH: "/usr/local:/usr"
      PKG_CONFIG_PATH: "/usr/local/lib/pkgconfig:/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig"
    cmds:
      # - sudo apt-get install -y git build-essential wget tar gzip pkgconf pkg-config libpixman-1-dev
      - wget https://github.com/hyprwm/hyprlang/archive/refs/tags/v{{.VERSION}}.tar.gz
      - tar -xvzf v{{.VERSION}}.tar.gz
      - |
        cd hyprlang-{{.VERSION}}
        $CMAKE --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX -S . -B ./build
        $CMAKE --build ./build --config Release --target hyprlang -j`nproc 2>/dev/null || getconf _NPROCESSORS_CONF`
        sudo $CMAKE --install build
    status:
      - test -f $PREFIX/lib/libhyprlang.so

  hyprgraphics:
    dir: "{{.PWD}}/hypr"
    deps: [hyprutils]
    vars:
      VERSION: "0.3.0"
    env:
      CC: "{{.PREFIX}}/bin/gcc"
      CXX: "{{.PREFIX}}/bin/g++"
      CMAKE_PREFIX_PATH: "/usr/local:/usr"
      PKG_CONFIG_PATH: "/usr/local/lib/pkgconfig:/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig"
    cmds:
      - sudo apt-get install -y file libjxl-dev libmagic-dev librsvg2-dev libjpeg-turbo8-dev libcairo2-dev libpango1.0-dev libpng-dev libwebp-dev
      - wget https://github.com/hyprwm/hyprgraphics/archive/refs/tags/v{{.VERSION}}.tar.gz
      - tar -xvzf v{{.VERSION}}.tar.gz
      - |
        cd hyprgraphics-{{.VERSION}}
        $CMAKE --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX -S . -B ./build
        $CMAKE --build ./build --config Release --target all -j`nproc 2>/dev/null || getconf _NPROCESSORS_CONF`
        sudo $CMAKE --install build
    status:
      - test -f $PREFIX/lib/libhyprgraphics.so

  hyprcursor:
    dir: "{{.PWD}}/hypr"
    deps: [hyprlang]
    vars:
      VERSION: "0.1.13"
    env:
      CC: "{{.PREFIX}}/bin/gcc"
      CXX: "{{.PREFIX}}/bin/g++"
      CMAKE_PREFIX_PATH: "/usr/local:/usr"
      PKG_CONFIG_PATH: "/usr/local/lib/pkgconfig:/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig"
    cmds:
      - sudo apt-get install -y file libjxl-dev libmagic-dev librsvg2-dev libjpeg-turbo8-dev libcairo2-dev libpango1.0-dev libpng-dev libwebp-dev libzip-dev libtomlplusplus-dev
      - wget https://github.com/hyprwm/hyprcursor/archive/refs/tags/v{{.VERSION}}.tar.gz
      - tar -xvzf v{{.VERSION}}.tar.gz
      - |
        cd hyprcursor-{{.VERSION}}
        $CMAKE --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX -S . -B ./build
        $CMAKE --build ./build --config Release --target all -j`nproc 2>/dev/null || getconf _NPROCESSORS_CONF`
        sudo $CMAKE --install build
    status:
      - test -f $PREFIX/lib/libhyprcursor.so
