# https://taskfile.dev

version: '3'

tasks:

  build-docker-ubuntu-non-root-image:
    cmd: docker build -t ubuntu-non_root:noble -f Dockerfile.ubuntu-non_root .
  
  wayland:
    deps: [build-docker-ubuntu-non-root-image]
    cmds:
      - docker build -t wayland-build:0.1 -f Dockerfile.wayland .
      - docker run --mount type=bind,src=/usr/local,dst=/usr/local wayland-build:0.1
  
  wayland-protocols:
    deps: [wayland]
    cmds:
      - docker build -t wayland-protocols-build:0.1 -f Dockerfile.wayland-protocols .
      - docker run --mount type=bind,src=/usr/local,dst=/usr/local wayland-protocols-build:0.1
  
  
