# https://taskfile.dev

version: "3"

env:
  PREFIX: "/usr/local"

vars:
  DIR: "./deps"

tasks:
  noble-sudo:
    dir: "{{.DIR}}"
    cmd: docker build -t {{.TASK}} -f Dockerfile.{{.TASK}} .
    status:
      - docker image inspect {{.TASK}} > /dev/null 2>&1

  wayland:
    deps: [noble-sudo]
    dir: "{{.DIR}}"
    cmds:
      - docker build -t {{.TASK}} -f Dockerfile.{{.TASK}} .
      - docker create --name {{.TASK}} {{.TASK}}
      - sudo docker cp {{.TASK}}:$PREFIX/. $PREFIX
    status:
      - test -f $PREFIX/lib/x86_64-linux-gnu/libwayland-server.so

  wayland-protocols:
    deps: [wayland]
    dir: "{{.DIR}}"
    cmds:
      - docker build -t {{.TASK}} -f Dockerfile.{{.TASK}} .
      - docker create --name {{.TASK}} {{.TASK}}
      - sudo docker cp {{.TASK}}:$PREFIX/. $PREFIX
    status:
      - test -d $PREFIX/include/wayland-protocols

  libdisplay-info:
    deps: [noble-sudo]
    dir: "{{.DIR}}"
    cmds:
      - docker build -t {{.TASK}} -f Dockerfile.{{.TASK}} .
      - docker create --name {{.TASK}} {{.TASK}}
      - sudo docker cp {{.TASK}}:$PREFIX/. $PREFIX
    status:
      - test -f $PREFIX/lib/x86_64-linux-gnu/libdisplay-info.so

  libinput:
    deps: [noble-sudo]
    dir: "{{.DIR}}"
    cmds:
      - docker build -t {{.TASK}} -f Dockerfile.{{.TASK}} .
      - docker create --name {{.TASK}} {{.TASK}}
      - sudo docker cp {{.TASK}}:$PREFIX/. $PREFIX
    status:
      - test -f $PREFIX/lib/x86_64-linux-gnu/libinput.so

  libxcb-errors:
    deps: [noble-sudo]
    dir: "{{.DIR}}"
    cmds:
      - docker build -t {{.TASK}} -f Dockerfile.{{.TASK}} .
      - docker create --name {{.TASK}} {{.TASK}}
      - sudo docker cp {{.TASK}}:$PREFIX/. $PREFIX
    status:
      - test -f $PREFIX/lib/libxcb-errors.so

  gcc:
    deps: [noble-sudo]
    dir: "{{.DIR}}"
    cmds:
      - docker build -t {{.TASK}} -f Dockerfile.{{.TASK}} .
      - docker create --name {{.TASK}} {{.TASK}}
      - sudo docker cp {{.TASK}}:$PREFIX/. $PREFIX
    status:
      - test -f /usr/local/bin/gcc
      - test -f /usr/local/bin/g++

  qt6:
    deps: [noble-sudo]
    dir: "{{.DIR}}"
    cmds:
      - docker build -t {{.TASK}} -f Dockerfile.{{.TASK}} .
      - docker create --name {{.TASK}} {{.TASK}}
      - sudo docker cp {{.TASK}}:$PREFIX/. $PREFIX
    status:
      - test -f /usr/local/lib/libQt6Core.so

  roc-toolkit:
    deps: [noble-sudo]
    cmds:
      - docker build -t {{.TASK}} -f Dockerfile.{{.TASK}} .
      - docker create --name {{.TASK}} {{.TASK}}
      - sudo docker cp {{.TASK}}:$PREFIX/. $PREFIX
    status:
      - test -f $PREFIX/lib/libroc.so

  libcamera:
    deps: [noble-sudo]
    cmds:
      - docker build -t {{.TASK}} -f Dockerfile.{{.TASK}} .
      - docker create --name {{.TASK}} {{.TASK}}
      - sudo docker cp {{.TASK}}:$PREFIX/. $PREFIX
    status:
      - test -f $PREFIX/lib/x86_64-linux-gnu/libcamera.so

  pipewire:
    deps: [roc-toolkit, libcamera]
    cmds:
      - docker build -t {{.TASK}} -f Dockerfile.{{.TASK}} .
      - docker create --name {{.TASK}} {{.TASK}}
      - sudo docker cp {{.TASK}}:$PREFIX/. $PREFIX
    status:
      - test -f $PREFIX/lib/x86_64-linux-gnu/libpipewire*.so

  iniparser:
    deps: [noble-sudo]
    cmds:
      - docker build -t {{.TASK}} -f Dockerfile.{{.TASK}} .
      - docker create --name {{.TASK}} {{.TASK}}
      - sudo docker cp {{.TASK}}:$PREFIX/. $PREFIX
    status:
      - test -f $PREFIX/lib/libiniparser.so

  uwsm:
    deps: [noble-sudo]
    dir: "{{.DIR}}"
    vars:
      VERSION: 0.24.3
    cmds:
      - mkdir -p {{.TASK}}
      - docker build -t {{.TASK}} -f Dockerfile.{{.TASK}} .
      - docker create --name {{.TASK}} {{.TASK}}
      - docker cp {{.TASK}}:/home/ubuntu/uwsm_{{.VERSION}}-1~local0_all.deb ./{{.TASK}}/
      - docker cp {{.TASK}}:/home/ubuntu/uwsm-{{.VERSION}}/uwsm-build-deps_{{.VERSION}}-1~local0_all.deb ./{{.TASK}}/
      - sudo apt-get install -y ./{{.TASK}}/*.deb

  xdg-desktop-portal:
    deps: [noble-sudo]
    dir: "{{.DIR}}"
    vars:
      VERSION: 1.20.3
    cmds:
      - docker build -t {{.TASK}} -f Dockerfile.{{.TASK}} .
      - docker create --name {{.TASK}} {{.TASK}}
      - sudo docker cp {{.TASK}}:$PREFIX/. $PREFIX
    status:
      - test -f $PREFIX/libexec/{{.TASK}}

  gtk4-layer-shell:
    deps: [noble-sudo]
    dir: "{{.DIR}}"
    vars:
      VERSION: 1.20.3
    cmds:
      - docker build -t {{.TASK}} -f Dockerfile.{{.TASK}} .
      - docker create --name {{.TASK}} {{.TASK}}
      - sudo docker cp {{.TASK}}:$PREFIX/. $PREFIX
    status:
      - test -f $PREFIX/lib/x86_64-linux-gnu/libgtk4-layer-shell.so
